// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwD_nE4FfDEvJ5gFlgBAEUmLnBDDHNlRs',
    appId: '1:949191366590:web:045dabd43beabc0e710bef',
    messagingSenderId: '949191366590',
    projectId: 'cellz-beta',
    authDomain: 'cellz-beta.firebaseapp.com',
    storageBucket: 'cellz-beta.appspot.com',
    measurementId: 'G-VYCWCE7DDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTF8A09aRmWY5wJCx-i6gr1hNBMd8ql1A',
    appId: '1:949191366590:android:912503c33485ab0d710bef',
    messagingSenderId: '949191366590',
    projectId: 'cellz-beta',
    storageBucket: 'cellz-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoYysdxxGZQpOyjf4L4bo4uvhaP2Fj0M',
    appId: '1:949191366590:ios:e73aead5831037e6710bef',
    messagingSenderId: '949191366590',
    projectId: 'cellz-beta',
    storageBucket: 'cellz-beta.appspot.com',
    iosBundleId: 'com.example.cellzM3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoYysdxxGZQpOyjf4L4bo4uvhaP2Fj0M',
    appId: '1:949191366590:ios:5ece956b3e714529710bef',
    messagingSenderId: '949191366590',
    projectId: 'cellz-beta',
    storageBucket: 'cellz-beta.appspot.com',
    iosBundleId: 'com.example.cellzM3.RunnerTests',
  );
}
